version: '3'

services:
  redis:
    image: redis:alpine
    container_name: cache
    networks:
      - app-network

  publisher:
    build:
      context: ./packages/publisher
    container_name: publisher
    restart: on-failure
    links:
      - redis
    depends_on:
      - redis
    environment:
      - SERVICE_PORT=3000
      - REDIS_HOST=redis://cache
      - REDIS_PORT=6379
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./packages/publisher:/usr/src/pangaea
    networks:
      - app-network
  
  subscriber:
    build:
      context: ./packages/subscriber
    container_name: subscriber
    restart: on-failure
    links:
      - redis
    depends_on:
      - redis
    environment:
      - SERVICE_PORT=8000
      - REDIS_HOST=redis://cache
      - REDIS_PORT=6379
      - NODE_ENV=production
    ports:
      - "8000:8000"
    volumes:
      - ./packages/subscriber:/usr/src/pangaea
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
